org: rafaelram
service: api-web-scraping

provider:
  name: aws
  runtime: python3.13
  # Default memory size for functions (default: 1024MB)
  memorySize: 1024
  timeout: 30
  stage: ${opt:stage, 'dev'}
  iam:
    role: arn:aws:iam::969784661290:role/LabRole

functions:
  scrape_table:
    handler: scrap_table.lambda_handler  # Asegúrarse de que el nombre del archivo y la función coincidan
    package:
      include:
        - ./**  # Incluir todo el contenido del directorio
    events:
      - http:
          path: /scrape/table
          method: get
          cors: true
          integration: lambda
  scrape_igp:  # Nueva función para scraping de sismos IGP
    handler: scrap_igp.lambda_handler
    package:
      include:
        - ./**
    events:
      - http:
          path: /scrape/igp
          method: get
          cors: true
          integration: lambda

resources:
  Resources:
    TablaWebScrapping:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TablaWebScrapping
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    # BUCKET DEPLOY   
    MyS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: my-s3rrh-bucket-${sls:stage}-${aws:accountId}
    
    TablaSismosIGP:  # Nueva tabla para almacenar los sismos del IGP
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TablaSismosIGP
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
